# Generated by Django 4.2 on 2023-04-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='variable',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
