# Generated by Django 4.2 on 2023-04-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_variable'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='vote',
            field=models.CharField(default='a', max_length=1),
            preserve_default=False,
        ),
    ]
